Repository etcd-io/auger, pull requests merged in 2024-08, with the labels that each got.

#87 Bump go & golangci-lint and pin actions dependencies
  .github/dependabot.yml
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
  Dockerfile
  Makefile
  README.md
  go.mod
Labels: approved, size/M

#91 Move the go directive version to toolchain
  go.mod
Labels: size/XS, approved

#82 Add `augerctl get`
  augerctl/README.md
  augerctl/command/ctl.go
  augerctl/command/get_command.go
  augerctl/command/global.go
  augerctl/command/printer.go
  augerctl/command/printer_yaml.go
  augerctl/main.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_get.go
  pkg/client/util.go
  pkg/client/util_test.go
Labels: approved, size/XXL

#95 Bump k8s to 1.31
  go.mod
  go.sum
  pkg/scheme/scheme.go
Labels: approved, size/M, lgtm

#96 Bump go toolchain to 1.23.0
  .github/workflows/static-analysis.yaml
  Dockerfile
  Makefile
  go.mod
Labels: size/S, approved

#104 Revert "Bump golang from `d0b3155` to `613a108`"
  Dockerfile
Labels: size/XS, approved

#108 Added CGO_ENABLED=0 to build args
  Makefile
Labels: size/XS, approved, lgtm
