Repository etcd-io/auger, pull requests merged in 2025-03, with the labels that each got.

#219 chore: use go tools from go 1.24
  Makefile
  go.mod
  go.sum
  scripts/fix.sh
  tools/.golangci.yaml
Labels: approved, size/XXL

#220 chore: enable more rules from revive
  augerctl/command/global.go
  cmd/analyze.go
  cmd/checksum.go
  cmd/decode.go
  cmd/encode.go
  cmd/extract.go
  pkg/client/client_get.go
  pkg/client/util.go
  pkg/data/data.go
  pkg/encoding/encoding.go
  pkg/scheme/init.go
  tools/.golangci.yaml
Labels: approved, size/M

#221 chore: align golangci-lint config with etcd
  augerctl/command/get_command.go
  cmd/decode.go
  cmd/extract.go
  pkg/data/data.go
  pkg/encoding/encoding.go
  pkg/scheme/init.go
  tools/.golangci.yaml
Labels: approved, size/M

#222 Update golang toolchain to version 1.24.1
  go.mod
Labels: ok-to-test, size/XS, approved
