Repository etcd-io/auger, pull requests merged in 2025-02, with the labels that each got.

#201 Update golang toolchain to version 1.23.6
  go.mod
Labels: size/XS

#209 Bump go linter 1.24
  .github/workflows/static-analysis.yaml
Labels: size/XS, approved

#216 bump golangci-lint v1.64.5
  .github/workflows/static-analysis.yaml
Labels: size/XS

#208 Bump go 1.24.0
  go.mod
Labels: size/XS, approved

#217 chore: clean up golangci-lint
  tools/.golangci.yaml
Labels: approved, size/M
